# Welcome to Jekyll!
#

# Site settings
title: Andrewyu.dev
description:
  Programming
owner: Andrew Yu # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: 2521andy@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/YtAirWolfXD
  github: https://github.com/AirWolfXD
  linkedin-square: https://linkedin.com/in/andrew-yu-22a3a41b1/
  facebook-official: https://facebook.com/andrew.yu.98622733
  #email: /contact/
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCPsjViD3xB_yWqXjc5aGMyw
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:
nav_list:
  Home: '/index.html'
  Blog: '/Blog.html'
  Projects: '/Projects.html'
  Courses: '/Courses.html'
  Usaco: '/Usaco.html'
  Games: '/Games.html'
  Videos: '/Videos.html'
  Contact Us: '/ContactUs.html'

# Build settings
markdown: kramdown
#sass:
#  style: compressed
